# Generated by Django 4.1.7 on 2023-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.CharField(default='Мастер по маникюру и педикюру', max_length=255),
        ),
    ]
