# Generated by Django 4.1.7 on 2023-03-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
