# Generated by Django 4.1.7 on 2023-04-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('BK', 'Booked')], default='AV', max_length=2),
        ),
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, default='users/profile_placeholder.jpg', upload_to='users/'),
        ),
        migrations.AddField(
            model_name='master',
            name='schedule',
            field=models.FileField(blank=True, upload_to='schedules/'),
        ),
    ]
