# Generated by Django 4.1.7 on 2023-03-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_master_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(blank=True, default='images/profile-placeholder.png', upload_to='images/'),
        ),
    ]
